#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta#!/bin/bash
head --lines=3 iacta
